### ISSUE TITLE
Bogue - amélioration des différentes éléments

### ISSUE THREAD

**Issue by WestFR** [RBische/outer-space-manager-api#23]
**Bogue 1  (sur un utilisateur déjà existant ) :**

- Bogue constaté lors de la mise à jour d'un bâtiment, d'une recherche technologique ou de l'achat de vaisseaux.

- Les différentes requêtes sont bien lancées, les code de retour sont bon. Cependant les différentes éléments restent dans une phase **"Amélioration en cours"**

- Conséquence : Les différents éléments ne sortent jamais de la phase **"Amélioration en cours"** même après un long temps d'attente.

**Bogue 2 (sur un nouvel utilisateur) :**

- Bogue constaté lors de la mise à jour d'un bâtiment ou d'une recherche technologique.

- Les différentes requêtes sont bien lancées et les code de retour sont bon. Cependant, lors de l'affichage de la liste des bâtiments ou recherche, nous obtenons une valeur **null pour l'élement level**

- Conséquence :  L'écran Bâtiments & Recherche technologique n'arrive pas à s'afficher car les valeurs remontées sont "null"

**Comment by RBische** [comment]
Should be fixed
